"""add verification backbone

Revision ID: 5014402fb40f
Revises: 35c4a78370eb
Create Date: 2026-10-03 01:04:27.487697

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5014402fb40f"
down_revision: str | Sequence[str] | None = "35c4a78370eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum("USER", "SYSTEM", "WORKER", "MODEL", name="actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "model_runs",
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column(
            "task",
            sa.Enum(
                "CONTENT_CLASSIFICATION",
                "CLAIM_EXTRACTION",
                "RETRIEVAL",
                "RERANKING",
                "NLI",
                "FUSION",
                name="prediction_task",
            ),
            nullable=False,
        ),
        sa.Column("framework", sa.String(length=128), nullable=True),
        sa.Column("mlflow_run_id", sa.String(length=255), nullable=True),
        sa.Column("artifact_uri", sa.String(length=2048), nullable=True),
        sa.Column("dataset_version", sa.String(length=255), nullable=True),
        sa.Column("git_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
        sa.UniqueConstraint("mlflow_run_id", name=op.f("uq_model_runs_mlflow_run_id")),
    )
    op.create_index(op.f("ix_model_runs_model_name"), "model_runs", ["model_name"], unique=False)
    op.create_index(op.f("ix_model_runs_task"), "model_runs", ["task"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("claim_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="analysis_job_status"
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("job_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_analysis_jobs_claim_id_claims"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_analysis_jobs_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    op.create_index(op.f("ix_analysis_jobs_claim_id"), "analysis_jobs", ["claim_id"], unique=False)
    op.create_index(
        op.f("ix_analysis_jobs_document_id"), "analysis_jobs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_jobs_request_id"), "analysis_jobs", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_jobs_status"), "analysis_jobs", ["status"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("atomic_claim_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("passage_text", sa.Text(), nullable=False),
        sa.Column("passage_hash", sa.String(length=64), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("retrieval_score", sa.Float(), nullable=True),
        sa.Column("reranker_score", sa.Float(), nullable=True),
        sa.Column(
            "stance",
            sa.Enum("SUPPORT", "REFUTE", "NEUTRAL", "INSUFFICIENT", name="evidence_stance"),
            nullable=True,
        ),
        sa.Column("stance_confidence", sa.Float(), nullable=True),
        sa.Column("is_independent_source", sa.Boolean(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["atomic_claim_id"],
            ["atomic_claims.id"],
            name=op.f("fk_evidence_atomic_claim_id_atomic_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_evidence_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(
        op.f("ix_evidence_atomic_claim_id"), "evidence", ["atomic_claim_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_document_id"), "evidence", ["document_id"], unique=False)
    op.create_index(op.f("ix_evidence_passage_hash"), "evidence", ["passage_hash"], unique=False)
    op.create_index(op.f("ix_evidence_stance"), "evidence", ["stance"], unique=False)
    op.create_table(
        "verification_results",
        sa.Column("atomic_claim_id", sa.UUID(), nullable=False),
        sa.Column("analysis_job_id", sa.UUID(), nullable=True),
        sa.Column("fusion_model_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "verdict",
            sa.Enum(
                "SUPPORTED",
                "LIKELY_SUPPORTED",
                "REFUTED",
                "LIKELY_REFUTED",
                "CONFLICTING",
                "INSUFFICIENT",
                name="verification_verdict",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.Float(), nullable=True),
        sa.Column("corroboration_score", sa.Float(), nullable=True),
        sa.Column("support_count", sa.Integer(), nullable=False),
        sa.Column("refute_count", sa.Integer(), nullable=False),
        sa.Column("neutral_count", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("decision_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_verification_results_analysis_job_id_analysis_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["atomic_claim_id"],
            ["atomic_claims.id"],
            name=op.f("fk_verification_results_atomic_claim_id_atomic_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fusion_model_run_id"],
            ["model_runs.id"],
            name=op.f("fk_verification_results_fusion_model_run_id_model_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
    )
    op.create_index(
        op.f("ix_verification_results_analysis_job_id"),
        "verification_results",
        ["analysis_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_results_atomic_claim_id"),
        "verification_results",
        ["atomic_claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_results_verdict"), "verification_results", ["verdict"], unique=False
    )
    op.create_table(
        "predictions",
        sa.Column("atomic_claim_id", sa.UUID(), nullable=True),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("model_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "task",
            sa.Enum(
                "CONTENT_CLASSIFICATION",
                "CLAIM_EXTRACTION",
                "RETRIEVAL",
                "RERANKING",
                "NLI",
                "FUSION",
                name="prediction_task",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["atomic_claim_id"],
            ["atomic_claims.id"],
            name=op.f("fk_predictions_atomic_claim_id_atomic_claims"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_predictions_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
            name=op.f("fk_predictions_model_run_id_model_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(
        op.f("ix_predictions_atomic_claim_id"), "predictions", ["atomic_claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_predictions_evidence_id"), "predictions", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_predictions_model_run_id"), "predictions", ["model_run_id"], unique=False
    )
    op.create_index(op.f("ix_predictions_task"), "predictions", ["task"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_predictions_task"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_model_run_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_evidence_id"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_atomic_claim_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_verification_results_verdict"), table_name="verification_results")
    op.drop_index(
        op.f("ix_verification_results_atomic_claim_id"), table_name="verification_results"
    )
    op.drop_index(
        op.f("ix_verification_results_analysis_job_id"), table_name="verification_results"
    )
    op.drop_table("verification_results")
    op.drop_index(op.f("ix_evidence_stance"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_passage_hash"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_document_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_atomic_claim_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_analysis_jobs_status"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_request_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_document_id"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_claim_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_model_runs_task"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_model_name"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
